
; size_t ba_priority_queue_capacity_fastcall(ba_priority_queue_t *q)

SECTION code_clib
SECTION code_adt_ba_priority_queue

PUBLIC _ba_priority_queue_capacity_fastcall

EXTERN asm_ba_priority_queue_capacity

defc _ba_priority_queue_capacity_fastcall = asm_ba_priority_queue_capacity
