
// automatically generated by m4 from headers in proto subdir


#ifndef __INPUT_HBIOS_H__
#define __INPUT_HBIOS_H__

#include <stdint.h>

///////////
// keyboard
///////////

extern int __LIB__ in_inkey(void) __smallc;


extern int __LIB__ in_test_key(void) __smallc;


extern void __LIB__ in_wait_key(void) __smallc;


extern void __LIB__ in_wait_nokey(void) __smallc;



extern uint16_t __LIB__ in_pause(uint16_t dur_ms) __smallc __z88dk_fastcall;



////////////
// joysticks
////////////

////////
// mouse
////////

#endif
