
// automatically generated by m4 from headers in proto subdir


#ifndef __INPUT_CPM_H__
#define __INPUT_CPM_H__

#include <stdint.h>

///////////
// keyboard
///////////

extern int __LIB__ in_inkey(void) __smallc;


extern int __LIB__ in_key_pressed(uint16_t scancode) __smallc __z88dk_fastcall;


extern uint16_t __LIB__ in_key_scancode(int c) __smallc __z88dk_fastcall;



extern uint16_t __LIB__ in_pause(uint16_t dur_ms) __smallc __z88dk_fastcall;


extern int __LIB__ in_test_key(void) __smallc;


extern void __LIB__ in_wait_key(void) __smallc;


extern void __LIB__ in_wait_nokey(void) __smallc;



////////////
// joysticks
////////////

extern uint16_t __LIB__ in_stick_keyboard(udk_t *u) __smallc __z88dk_fastcall;



////////
// mouse
////////

#endif
