
// automatically generated by m4 from headers in proto subdir


#ifndef __ADT_P_FORWARD_LIST_ALT__
#define __ADT_P_FORWARD_LIST_ALT__

#include <stddef.h>

// DATA STRUCTURES

typedef struct p_forward_list_alt_s
{

   void       *head;
   void       *tail;

} p_forward_list_alt_t;

extern void __LIB__ *p_forward_list_alt_back(p_forward_list_alt_t *ls) __smallc __z88dk_fastcall;


extern void __LIB__ p_forward_list_alt_clear(p_forward_list_alt_t *ls) __smallc __z88dk_fastcall;


extern int __LIB__ p_forward_list_alt_empty(p_forward_list_alt_t *ls) __smallc __z88dk_fastcall;


extern void __LIB__ *p_forward_list_alt_front(p_forward_list_alt_t *ls) __smallc __z88dk_fastcall;


extern void __LIB__ p_forward_list_alt_init(void *p) __smallc __z88dk_fastcall;


extern void __LIB__ *p_forward_list_alt_insert_after(p_forward_list_alt_t *ls,void *ls_item,void *item) __smallc;
extern void __LIB__ *p_forward_list_alt_insert_after_callee(p_forward_list_alt_t *ls,void *ls_item,void *item) __smallc __z88dk_callee;
#define p_forward_list_alt_insert_after(a,b,c) p_forward_list_alt_insert_after_callee(a,b,c)


extern void __LIB__ *p_forward_list_alt_next(void *item) __smallc __z88dk_fastcall;


extern void __LIB__ *p_forward_list_alt_pop_back(p_forward_list_alt_t *ls) __smallc __z88dk_fastcall;


extern void __LIB__ *p_forward_list_alt_pop_front(p_forward_list_alt_t *ls) __smallc __z88dk_fastcall;


extern void __LIB__ *p_forward_list_alt_prev(p_forward_list_alt_t *ls,void *next) __smallc;
extern void __LIB__ *p_forward_list_alt_prev_callee(p_forward_list_alt_t *ls,void *next) __smallc __z88dk_callee;
#define p_forward_list_alt_prev(a,b) p_forward_list_alt_prev_callee(a,b)


extern void __LIB__ p_forward_list_alt_push_back(p_forward_list_alt_t *ls,void *item) __smallc;
extern void __LIB__ p_forward_list_alt_push_back_callee(p_forward_list_alt_t *ls,void *item) __smallc __z88dk_callee;
#define p_forward_list_alt_push_back(a,b) p_forward_list_alt_push_back_callee(a,b)


extern void __LIB__ p_forward_list_alt_push_front(p_forward_list_alt_t *ls,void *item) __smallc;
extern void __LIB__ p_forward_list_alt_push_front_callee(p_forward_list_alt_t *ls,void *item) __smallc __z88dk_callee;
#define p_forward_list_alt_push_front(a,b) p_forward_list_alt_push_front_callee(a,b)


extern void __LIB__ *p_forward_list_alt_remove(p_forward_list_alt_t *ls,void *item) __smallc;
extern void __LIB__ *p_forward_list_alt_remove_callee(p_forward_list_alt_t *ls,void *item) __smallc __z88dk_callee;
#define p_forward_list_alt_remove(a,b) p_forward_list_alt_remove_callee(a,b)


extern void __LIB__ *p_forward_list_alt_remove_after(p_forward_list_alt_t *ls,void *ls_item) __smallc;
extern void __LIB__ *p_forward_list_alt_remove_after_callee(p_forward_list_alt_t *ls,void *ls_item) __smallc __z88dk_callee;
#define p_forward_list_alt_remove_after(a,b) p_forward_list_alt_remove_after_callee(a,b)


extern size_t __LIB__ p_forward_list_alt_size(p_forward_list_alt_t *ls) __smallc __z88dk_fastcall;



#endif
