
;; clib rodata segments ;;;;;;;

section rodata_align_256
section rodata_align_128
section rodata_align_64
section rodata_align_32
section rodata_align_16
section rodata_align_8
section rodata_align_4
section rodata_align_2
section rodata_arch
section rodata_env
section rodata_error_strings
section rodata_error_string_end
defb 0
section rodata_fcntl
section rodata_font_4x8
section rodata_font_8x8
section rodata_font_fzx
section rodata_fp_math32
section rodata_input
section rodata_SMSlib
section rodata_sound_bit
section rodata_stdio
section rodata_stdlib

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
