#!/bin/bash
# i6_abbrvs
# find highly optimized abbreviations for Inform 6
# abbreviations.py script used by Hugo Labrande
# --------------------------------------------------
# Public Domain in 2021 by Stefan Vogt, Puddle Soft
# http://8bitgames.itch.io | http://puddlesoft.net
# --------------------------------------------------

cp ~/FictionTools/abbreviations.py .
python3 abbreviations.py -f
rm abbreviations.py
