#!/bin/bash
# Puddle BuildTools for PunyInform
# puny command line wrapper

inform=~/FictionTools/inform6
lib=~/Projects/8bit/Z-Machine/lib/lib/
v=-v3

main()
{
	$inform -d2esi $v +$lib $game
	game=`basename $game .inf`
	printf "\n"
	exit 0
}

usage()
{
	printf "PUDDLE BUILDTOOLS FOR PUNYINFORM V1.5\n"
	printf "Usage: puny game.inf\n"
	printf "       puny [-5] game.inf\n\n"
	printf "       -5 : create v5 release\n\n"
	printf "By default puny creates Z-code v3 releases.\n\n"
	exit 0
}

# Start of script

if [ ! -z `echo $1 | grep '.inf'` ]; then
	game=$1
	main
elif [ -z "$1" ]; then
	usage
fi	

while getopts 5:h opts
do
	case $opts in
		5) game=$2
		   v=-v5
		   main
		;;
		h) usage
		;;
		*) usage
		;;
	esac
done
