
// automatically generated by m4 from headers in proto subdir


#ifndef __INPUT_SMS_H__
#define __INPUT_SMS_H__

#include <stdint.h>

///////////
// keyboard
///////////

extern uint16_t in_pause(uint16_t dur_ms) __preserves_regs(iyl,iyh);
extern uint16_t in_pause_fastcall(uint16_t dur_ms) __preserves_regs(iyl,iyh) __z88dk_fastcall;
#define in_pause(a) in_pause_fastcall(a)


extern int in_test_key(void) __preserves_regs(b,c,d,e);

extern void in_wait_key(void) __preserves_regs(b,c,d,e,h,l);

extern void in_wait_nokey(void) __preserves_regs(b,c,d,e,h,l);


////////////
// joysticks
////////////

extern uint16_t in_stick_1(void) __preserves_regs(b,c,d,e);

extern uint16_t in_stick_2(void) __preserves_regs(b,c,d,e);


#endif
