INCLUDE "config_private.inc"

SECTION code_arch

PUBLIC _SYS_IY
defc _SYS_IY = __SYS_IY

PUBLIC _SYS_HLP
defc _SYS_HLP = __SYS_HLP

PUBLIC _SYSVAR_SWAP
defc _SYSVAR_SWAP = __SYSVAR_SWAP

PUBLIC _SYSVAR_STOO
defc _SYSVAR_STOO = __SYSVAR_STOO

PUBLIC _SYSVAR_YOUNGER
defc _SYSVAR_YOUNGER = __SYSVAR_YOUNGER

PUBLIC _SYSVAR_REGNUOY
defc _SYSVAR_REGNUOY = __SYSVAR_REGNUOY

PUBLIC _SYSVAR_ONERR
defc _SYSVAR_ONERR = __SYSVAR_ONERR

PUBLIC _SYSVAR_OLDHL
defc _SYSVAR_OLDHL = __SYSVAR_OLDHL

PUBLIC _SYSVAR_OLDBC
defc _SYSVAR_OLDBC = __SYSVAR_OLDBC

PUBLIC _SYSVAR_OLDAF
defc _SYSVAR_OLDAF = __SYSVAR_OLDAF

PUBLIC _SYSVAR_TARGET
defc _SYSVAR_TARGET = __SYSVAR_TARGET

PUBLIC _SYSVAR_RETADDR
defc _SYSVAR_RETADDR = __SYSVAR_RETADDR

PUBLIC _SYSVAR_BANKM
defc _SYSVAR_BANKM = __SYSVAR_BANKM

PUBLIC _SYSVAR_RAMRST
defc _SYSVAR_RAMRST = __SYSVAR_RAMRST

PUBLIC _SYSVAR_RAMERR
defc _SYSVAR_RAMERR = __SYSVAR_RAMERR

PUBLIC _SYSVAR_BAUD
defc _SYSVAR_BAUD = __SYSVAR_BAUD

PUBLIC _SYSVAR_SERFL
defc _SYSVAR_SERFL = __SYSVAR_SERFL

PUBLIC _SYSVAR_COL
defc _SYSVAR_COL = __SYSVAR_COL

PUBLIC _SYSVAR_WIDTH
defc _SYSVAR_WIDTH = __SYSVAR_WIDTH

PUBLIC _SYSVAR_TVPARS
defc _SYSVAR_TVPARS = __SYSVAR_TVPARS

PUBLIC _SYSVAR_FLAGS3
defc _SYSVAR_FLAGS3 = __SYSVAR_FLAGS3

PUBLIC _SYSVAR_BANK678
defc _SYSVAR_BANK678 = __SYSVAR_BANK678

PUBLIC _SYSVAR_FLAGN
defc _SYSVAR_FLAGN = __SYSVAR_FLAGN

PUBLIC _SYSVAR_MAXBNK
defc _SYSVAR_MAXBNK = __SYSVAR_MAXBNK

PUBLIC _SYSVAR_OLDSP
defc _SYSVAR_OLDSP = __SYSVAR_OLDSP

PUBLIC _SYSVAR_SYNRET
defc _SYSVAR_SYNRET = __SYSVAR_SYNRET

PUBLIC _SYSVAR_LASTV
defc _SYSVAR_LASTV = __SYSVAR_LASTV

PUBLIC _SYSVAR_TILEBNKL
defc _SYSVAR_TILEBNKL = __SYSVAR_TILEBNKL

PUBLIC _SYSVAR_TILEML
defc _SYSVAR_TILEML = __SYSVAR_TILEML

PUBLIC _SYSVAR_TILEBNK2
defc _SYSVAR_TILEBNK2 = __SYSVAR_TILEBNK2

PUBLIC _SYSVAR_TILEM2
defc _SYSVAR_TILEM2 = __SYSVAR_TILEM2

PUBLIC _SYSVAR_NXTBNK
defc _SYSVAR_NXTBNK = __SYSVAR_NXTBNK

PUBLIC _SYSVAR_DATABNK
defc _SYSVAR_DATABNK = __SYSVAR_DATABNK

PUBLIC _SYSVAR_LODDRV
defc _SYSVAR_LODDRV = __SYSVAR_LODDRV

PUBLIC _SYSVAR_SAVDRV
defc _SYSVAR_SAVDRV = __SYSVAR_SAVDRV

PUBLIC _SYSVAR_L2SOFT
defc _SYSVAR_L2SOFT = __SYSVAR_L2SOFT

PUBLIC _SYSVAR_TILEWL
defc _SYSVAR_TILEWL = __SYSVAR_TILEWL

PUBLIC _SYSVAR_TILEW2
defc _SYSVAR_TILEW2 = __SYSVAR_TILEW2

PUBLIC _SYSVAR_TILEOFFL
defc _SYSVAR_TILEOFFL = __SYSVAR_TILEOFFL

PUBLIC _SYSVAR_TILEOFF2
defc _SYSVAR_TILEOFF2 = __SYSVAR_TILEOFF2

PUBLIC _SYSVAR_COORDSL
defc _SYSVAR_COORDSL = __SYSVAR_COORDSL

PUBLIC _SYSVAR_COORDS2
defc _SYSVAR_COORDS2 = __SYSVAR_COORDS2

PUBLIC _SYSVAR_COORDSULA
defc _SYSVAR_COORDSULA = __SYSVAR_COORDSULA

PUBLIC _SYSVAR_COORDSHR
defc _SYSVAR_COORDSHR = __SYSVAR_COORDSHR

PUBLIC _SYSVAR_COORDSHC
defc _SYSVAR_COORDSHC = __SYSVAR_COORDSHC

PUBLIC _SYSVAR_INKL
defc _SYSVAR_INKL = __SYSVAR_INKL

PUBLIC _SYSVAR_INK2
defc _SYSVAR_INK2 = __SYSVAR_INK2

PUBLIC _SYSVAR_ATTRULA
defc _SYSVAR_ATTRULA = __SYSVAR_ATTRULA

PUBLIC _SYSVAR_ATTRHR
defc _SYSVAR_ATTRHR = __SYSVAR_ATTRHR

PUBLIC _SYSVAR_ATTRHC
defc _SYSVAR_ATTRHC = __SYSVAR_ATTRHC

PUBLIC _SYSVAR_INKMASK
defc _SYSVAR_INKMASK = __SYSVAR_INKMASK

PUBLIC _SYSVAR_TMPVARS
defc _SYSVAR_TMPVARS = __SYSVAR_TMPVARS


PUBLIC _SYSVAR_TSTACK
defc _SYSVAR_TSTACK = __SYSVAR_TSTACK


PUBLIC _SYSVAR_KSTATE
defc _SYSVAR_KSTATE = __SYSVAR_KSTATE

PUBLIC _SYSVAR_LASTK
defc _SYSVAR_LASTK = __SYSVAR_LASTK

PUBLIC _SYSVAR_REPDEL
defc _SYSVAR_REPDEL = __SYSVAR_REPDEL

PUBLIC _SYSVAR_REPPER
defc _SYSVAR_REPPER = __SYSVAR_REPPER

PUBLIC _SYSVAR_DEFADD
defc _SYSVAR_DEFADD = __SYSVAR_DEFADD

PUBLIC _SYSVAR_KDATA
defc _SYSVAR_KDATA = __SYSVAR_KDATA

PUBLIC _SYSVAR_TVDATA
defc _SYSVAR_TVDATA = __SYSVAR_TVDATA

PUBLIC _SYSVAR_STRMS
defc _SYSVAR_STRMS = __SYSVAR_STRMS

PUBLIC _SYSVAR_CHARS
defc _SYSVAR_CHARS = __SYSVAR_CHARS

PUBLIC _SYSVAR_RASP
defc _SYSVAR_RASP = __SYSVAR_RASP

PUBLIC _SYSVAR_PIP
defc _SYSVAR_PIP = __SYSVAR_PIP

PUBLIC _SYSVAR_ERRNR
defc _SYSVAR_ERRNR = __SYSVAR_ERRNR

PUBLIC _SYSVAR_FLAGS
defc _SYSVAR_FLAGS = __SYSVAR_FLAGS

PUBLIC _SYSVAR_TVFLAG
defc _SYSVAR_TVFLAG = __SYSVAR_TVFLAG

PUBLIC _SYSVAR_ERRSP
defc _SYSVAR_ERRSP = __SYSVAR_ERRSP

PUBLIC _SYSVAR_LISTSP
defc _SYSVAR_LISTSP = __SYSVAR_LISTSP

PUBLIC _SYSVAR_MODE
defc _SYSVAR_MODE = __SYSVAR_MODE

PUBLIC _SYSVAR_NEWPPC
defc _SYSVAR_NEWPPC = __SYSVAR_NEWPPC

PUBLIC _SYSVAR_NSPPC
defc _SYSVAR_NSPPC = __SYSVAR_NSPPC

PUBLIC _SYSVAR_PPC
defc _SYSVAR_PPC = __SYSVAR_PPC

PUBLIC _SYSVAR_SUBPPC
defc _SYSVAR_SUBPPC = __SYSVAR_SUBPPC

PUBLIC _SYSVAR_BORDCR
defc _SYSVAR_BORDCR = __SYSVAR_BORDCR

PUBLIC _SYSVAR_EPPC
defc _SYSVAR_EPPC = __SYSVAR_EPPC

PUBLIC _SYSVAR_VARS
defc _SYSVAR_VARS = __SYSVAR_VARS

PUBLIC _SYSVAR_DEST
defc _SYSVAR_DEST = __SYSVAR_DEST

PUBLIC _SYSVAR_CHANS
defc _SYSVAR_CHANS = __SYSVAR_CHANS

PUBLIC _SYSVAR_CURCHL
defc _SYSVAR_CURCHL = __SYSVAR_CURCHL

PUBLIC _SYSVAR_PROG
defc _SYSVAR_PROG = __SYSVAR_PROG

PUBLIC _SYSVAR_NXTLIN
defc _SYSVAR_NXTLIN = __SYSVAR_NXTLIN

PUBLIC _SYSVAR_DATADD
defc _SYSVAR_DATADD = __SYSVAR_DATADD

PUBLIC _SYSVAR_ELINE
defc _SYSVAR_ELINE = __SYSVAR_ELINE

PUBLIC _SYSVAR_KCUR
defc _SYSVAR_KCUR = __SYSVAR_KCUR

PUBLIC _SYSVAR_CHADD
defc _SYSVAR_CHADD = __SYSVAR_CHADD

PUBLIC _SYSVAR_XPTR
defc _SYSVAR_XPTR = __SYSVAR_XPTR

PUBLIC _SYSVAR_WORKSP
defc _SYSVAR_WORKSP = __SYSVAR_WORKSP

PUBLIC _SYSVAR_STKBOT
defc _SYSVAR_STKBOT = __SYSVAR_STKBOT

PUBLIC _SYSVAR_STKEND
defc _SYSVAR_STKEND = __SYSVAR_STKEND

PUBLIC _SYSVAR_BREG
defc _SYSVAR_BREG = __SYSVAR_BREG

PUBLIC _SYSVAR_MEM
defc _SYSVAR_MEM = __SYSVAR_MEM

PUBLIC _SYSVAR_FLAGS2
defc _SYSVAR_FLAGS2 = __SYSVAR_FLAGS2

PUBLIC _SYSVAR_DFSZ
defc _SYSVAR_DFSZ = __SYSVAR_DFSZ

PUBLIC _SYSVAR_STOP
defc _SYSVAR_STOP = __SYSVAR_STOP

PUBLIC _SYSVAR_OLDPPC
defc _SYSVAR_OLDPPC = __SYSVAR_OLDPPC

PUBLIC _SYSVAR_OSPPC
defc _SYSVAR_OSPPC = __SYSVAR_OSPPC

PUBLIC _SYSVAR_FLAGX
defc _SYSVAR_FLAGX = __SYSVAR_FLAGX

PUBLIC _SYSVAR_STRLEN
defc _SYSVAR_STRLEN = __SYSVAR_STRLEN

PUBLIC _SYSVAR_TADDR
defc _SYSVAR_TADDR = __SYSVAR_TADDR

PUBLIC _SYSVAR_SEED
defc _SYSVAR_SEED = __SYSVAR_SEED

PUBLIC _SYSVAR_FRAMES
defc _SYSVAR_FRAMES = __SYSVAR_FRAMES

PUBLIC _SYSVAR_UDG
defc _SYSVAR_UDG = __SYSVAR_UDG

PUBLIC _SYSVAR_COORDS
defc _SYSVAR_COORDS = __SYSVAR_COORDS

PUBLIC _SYSVAR_GMODE
defc _SYSVAR_GMODE = __SYSVAR_GMODE

PUBLIC _SYSVAR_PRCC
defc _SYSVAR_PRCC = __SYSVAR_PRCC

PUBLIC _SYSVAR_ECHOE
defc _SYSVAR_ECHOE = __SYSVAR_ECHOE

PUBLIC _SYSVAR_DFCC
defc _SYSVAR_DFCC = __SYSVAR_DFCC

PUBLIC _SYSVAR_DFCCL
defc _SYSVAR_DFCCL = __SYSVAR_DFCCL

PUBLIC _SYSVAR_SPOSN
defc _SYSVAR_SPOSN = __SYSVAR_SPOSN

PUBLIC _SYSVAR_SPOSNL
defc _SYSVAR_SPOSNL = __SYSVAR_SPOSNL

PUBLIC _SYSVAR_SCRCT
defc _SYSVAR_SCRCT = __SYSVAR_SCRCT

PUBLIC _SYSVAR_ATTRP
defc _SYSVAR_ATTRP = __SYSVAR_ATTRP

PUBLIC _SYSVAR_MASKP
defc _SYSVAR_MASKP = __SYSVAR_MASKP

PUBLIC _SYSVAR_ATTRT
defc _SYSVAR_ATTRT = __SYSVAR_ATTRT

PUBLIC _SYSVAR_MASKT
defc _SYSVAR_MASKT = __SYSVAR_MASKT

PUBLIC _SYSVAR_PFLAG
defc _SYSVAR_PFLAG = __SYSVAR_PFLAG

PUBLIC _SYSVAR_MEMBOT
defc _SYSVAR_MEMBOT = __SYSVAR_MEMBOT

PUBLIC _SYSVAR_NMIADD
defc _SYSVAR_NMIADD = __SYSVAR_NMIADD

PUBLIC _SYSVAR_RAMTOP
defc _SYSVAR_RAMTOP = __SYSVAR_RAMTOP

PUBLIC _SYSVAR_PRAMT
defc _SYSVAR_PRAMT = __SYSVAR_PRAMT
