
; int wa_priority_queue_empty_fastcall(wa_priority_queue_t *q)

SECTION code_clib
SECTION code_adt_wa_priority_queue

PUBLIC _wa_priority_queue_empty_fastcall

EXTERN asm_wa_priority_queue_empty

defc _wa_priority_queue_empty_fastcall = asm_wa_priority_queue_empty
