if (strcmp(argv[1],"die_die") == 0) { extern void run_die_die(void); run_die_die(); exit(0); } else
if (strcmp(argv[1],"die_xassert") == 0) { extern void run_die_xassert(void); run_die_xassert(); exit(0); } else
if (strcmp(argv[1],"die_check_alloc") == 0) { extern void run_die_check_alloc(void); run_die_check_alloc(); exit(0); } else
if (strcmp(argv[1],"fileutil_xfopen") == 0) { extern void run_fileutil_xfopen(void); run_fileutil_xfopen(); exit(0); } else
if (strcmp(argv[1],"fileutil_xfwrite_str") == 0) { extern void run_fileutil_xfwrite_str(void); run_fileutil_xfwrite_str(); exit(0); } else
if (strcmp(argv[1],"fileutil_xfwrite_bcount_str") == 0) { extern void run_fileutil_xfwrite_bcount_str(void); run_fileutil_xfwrite_bcount_str(); exit(0); } else
if (strcmp(argv[1],"fileutil_xfwrite_wcount_str") == 0) { extern void run_fileutil_xfwrite_wcount_str(void); run_fileutil_xfwrite_wcount_str(); exit(0); } else
if (strcmp(argv[1],"fileutil_xfread") == 0) { extern void run_fileutil_xfread(void); run_fileutil_xfread(); exit(0); } else
if (strcmp(argv[1],"fileutil_xfread_str") == 0) { extern void run_fileutil_xfread_str(void); run_fileutil_xfread_str(); exit(0); } else
if (strcmp(argv[1],"fileutil_xfread_bcount_str") == 0) { extern void run_fileutil_xfread_bcount_str(void); run_fileutil_xfread_bcount_str(); exit(0); } else
if (strcmp(argv[1],"fileutil_xfread_wcount_str") == 0) { extern void run_fileutil_xfread_wcount_str(void); run_fileutil_xfread_wcount_str(); exit(0); } else
if (strcmp(argv[1],"fileutil_xfseek") == 0) { extern void run_fileutil_xfseek(void); run_fileutil_xfseek(); exit(0); } else
