; void SMS_useFirstHalfTilesforSprites(_Bool usefirsthalf)

SECTION code_clib
SECTION code_SMSlib

PUBLIC SMS_useFirstHalfTilesforSprites

EXTERN asm_SMSlib_useFirstHalfTilesforSprites

defc SMS_useFirstHalfTilesforSprites = asm_SMSlib_useFirstHalfTilesforSprites
