; void SMS_loadBGPaletteHalfBrightness(void *palette)

SECTION code_clib
SECTION code_SMSlib

PUBLIC SMS_loadBGPaletteHalfBrightness

EXTERN asm_SMSlib_loadBGPaletteHalfBrightness

defc SMS_loadBGPaletteHalfBrightness = asm_SMSlib_loadBGPaletteHalfBrightness
