
// automatically generated by m4 from headers in proto subdir


#ifndef __NETINET_IN_H__
#define __NETINET_IN_H__

#include <stdint.h>

typedef uint16_t in_port_t;
typedef uint32_t in_addr_t;

#endif
