
// automatically generated by m4 from headers in proto subdir


#ifndef __STDALIGN_H__
#define __STDALIGN_H__

#define alignas _Alignas
#define alignof _Alignof

#define __alignas_is_defined 1
#define __alignof_is_defined 1

#endif
