INCLUDE "config_private.inc"

SECTION data_arch

PUBLIC _GLOBAL_SMS_VDP_R0R1
PUBLIC _GLOBAL_SMS_VDP_R0
PUBLIC _GLOBAL_SMS_VDP_R1

_GLOBAL_SMS_VDP_R0R1:

   defb __SMS_VDP_R0, __SMS_VDP_R1

defc _GLOBAL_SMS_VDP_R0 = _GLOBAL_SMS_VDP_R0R1
defc _GLOBAL_SMS_VDP_R1 = _GLOBAL_SMS_VDP_R0R1 + 1
