
; void *p_forward_list_remove_after_fastcall(void *list_item)

SECTION code_clib
SECTION code_adt_p_forward_list

PUBLIC _p_forward_list_remove_after_fastcall

EXTERN asm_p_forward_list_remove_after

defc _p_forward_list_remove_after_fastcall = asm_p_forward_list_remove_after
