
;; clib data segments ;;;;;;;;;

section data_alloc_balloc
section data_alloc_malloc
section data_arch
section data_fcntl
section data_fcntl_stdio_heap_head
section data_fcntl_stdio_heap_body
section data_fcntl_stdio_heap_tail
section data_fcntl_fdtable_body
section data_PSGlib
section data_SMSlib
section data_sound_bit
section data_stdio
section data_stdlib
section data_threads

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
