
// automatically generated by m4 from headers in proto subdir


#ifndef __INPUT_HBIOS_H__
#define __INPUT_HBIOS_H__

#include <stdint.h>

///////////
// keyboard
///////////

extern int in_inkey(void);


extern int in_test_key(void);


extern void in_wait_key(void);


extern void in_wait_nokey(void);



extern uint16_t in_pause(uint16_t dur_ms);



////////////
// joysticks
////////////

////////
// mouse
////////

#endif
