
; sp1_DrawUpdateStructIfNotRem(struct sp1_update *u)

SECTION code_clib
SECTION code_temp_sp1

PUBLIC _sp1_DrawUpdateStructIfNotRem_fastcall

EXTERN asm_sp1_DrawUpdateStructIfNotRem

defc _sp1_DrawUpdateStructIfNotRem_fastcall = asm_sp1_DrawUpdateStructIfNotRem
