
// automatically generated by m4 from headers in proto subdir


#ifndef __ADT_P_QUEUE_H__
#define __ADT_P_QUEUE_H__

#include <stddef.h>

// DATA STRUCTURES

typedef struct p_queue_s
{
   void       *head;
   void       *tail;

} p_queue_t;

extern void *p_queue_back(p_queue_t *q);


extern void p_queue_clear(p_queue_t *q);


extern int p_queue_empty(p_queue_t *q);


extern void *p_queue_front(p_queue_t *q);


extern void p_queue_init(void *p);


extern void *p_queue_pop(p_queue_t *q);


extern void p_queue_push(p_queue_t *q,void *item);


extern size_t p_queue_size(p_queue_t *q);



#endif
