
// automatically generated by m4 from headers in proto subdir


#ifndef __ADT_P_STACK_H__
#define __ADT_P_STACK_H__

#include <stddef.h>

// DATA STRUCTURES

typedef void* p_stack_t;

extern void p_stack_clear(p_stack_t *s);


extern int p_stack_empty(p_stack_t *s);


extern void p_stack_init(void *p);


extern void *p_stack_pop(p_stack_t *s);


extern void p_stack_push(p_stack_t *s,void *item);


extern size_t p_stack_size(p_stack_t *s);


extern void *p_stack_top(p_stack_t *s);



#endif
