
// automatically generated by m4 from headers in proto subdir


#ifndef __ADT_WA_PRIORITY_QUEUE_H__
#define __ADT_WA_PRIORITY_QUEUE_H__

#include <stddef.h>

// DATA STRUCTURES

typedef struct wa_priority_queue_s
{

   void       *compar;
   void       *data;
   size_t      size;
   size_t      capacity;

} wa_priority_queue_t;

extern size_t wa_priority_queue_capacity(wa_priority_queue_t *q);


extern void wa_priority_queue_clear(wa_priority_queue_t *q);


extern void *wa_priority_queue_data(wa_priority_queue_t *q);


extern void wa_priority_queue_destroy(wa_priority_queue_t *q);


extern int wa_priority_queue_empty(wa_priority_queue_t *q);


extern wa_priority_queue_t *wa_priority_queue_init(void *p,void *data,size_t capacity,void *compar);


extern void *wa_priority_queue_pop(wa_priority_queue_t *q);


extern int wa_priority_queue_push(wa_priority_queue_t *q,void *item);


extern int wa_priority_queue_resize(wa_priority_queue_t *q,size_t n);


extern size_t wa_priority_queue_size(wa_priority_queue_t *q);


extern void *wa_priority_queue_top(wa_priority_queue_t *q);



#endif
