
// automatically generated by m4 from headers in proto subdir


#ifndef __COMPRESS_H__
#define __COMPRESS_H__

// data compression / decompression

#include <compress/aplib.h>
#include <compress/zx7.h>

#endif
