
// automatically generated by m4 from headers in proto subdir


#ifndef __CTYPE_H__
#define __CTYPE_H__

extern int isalnum(int);


extern int isalpha(int);


extern int isascii(int);


extern int isbdigit(int);


extern int isblank(int);


extern int iscntrl(int);


extern int isdigit(int);


extern int isgraph(int);


extern int islower(int);


extern int isodigit(int);


extern int isprint(int);


extern int ispunct(int);


extern int isspace(int);


extern int isupper(int);


extern int isxdigit(int);


extern int toascii(int);


extern int tolower(int);


extern int toupper(int);



#endif
