
// automatically generated by m4 from headers in proto subdir


///////////////////////////////////////////////////////////
//                  SPRITE PACK v3.0                     //
//            aralbrec - April / May 2006                //
///////////////////////////////////////////////////////////
//                                                       //
//    Software sprite engine for bitmapped displays      //
//                                                       //
//    * Differential screen update                       //
//    * Any number and any size of sprites               //
//    * Clipping to character cell boundaries            //
//    * Background tile animation                        //
//                                                       //
//       See the wiki for documentation details          //
//             http://www.z88dk.org/wiki                 //
//                                                       //
///////////////////////////////////////////////////////////

#ifdef __SPECTRUM
#include <arch/zx/sp1.h>
#endif
