
; int wv_priority_queue_shrink_to_fit_fastcall(wv_priority_queue_t *q)

SECTION code_clib
SECTION code_adt_wv_priority_queue

PUBLIC _wv_priority_queue_shrink_to_fit_fastcall

EXTERN asm_wv_priority_queue_shrink_to_fit

defc _wv_priority_queue_shrink_to_fit_fastcall = asm_wv_priority_queue_shrink_to_fit
