
// automatically generated by m4 from headers in proto subdir


#ifndef __ALLOC_BALLOC_H__
#define __ALLOC_BALLOC_H__

#include <stddef.h>

extern void *balloc_addmem(unsigned char q,size_t num,size_t size,void *p);


extern void *balloc_alloc(unsigned char q);


extern size_t balloc_blockcount(unsigned char q);


extern void *balloc_firstfit(unsigned char q,unsigned char numq);


extern void balloc_free(void *p);


extern void *balloc_reset(unsigned char q);



#endif
