
// automatically generated by m4 from headers in proto subdir


#ifndef __ADT_BV_PRIORITY_QUEUE_H__
#define __ADT_BV_PRIORITY_QUEUE_H__

#include <stddef.h>

// DATA STRUCTURES

typedef struct bv_priority_queue_s
{

   void       *compar;
   void       *data;
   size_t      size;
   size_t      capacity;
   size_t      max_size;

} bv_priority_queue_t;

extern size_t __LIB__ bv_priority_queue_capacity(bv_priority_queue_t *q) __smallc __z88dk_fastcall;


extern void __LIB__ bv_priority_queue_clear(bv_priority_queue_t *q) __smallc __z88dk_fastcall;


extern void __LIB__ *bv_priority_queue_data(bv_priority_queue_t *q) __smallc __z88dk_fastcall;


extern void __LIB__ bv_priority_queue_destroy(bv_priority_queue_t *q) __smallc __z88dk_fastcall;


extern int __LIB__ bv_priority_queue_empty(bv_priority_queue_t *q) __smallc __z88dk_fastcall;


extern bv_priority_queue_t __LIB__ *bv_priority_queue_init(void *p,size_t capacity,size_t max_size,void *compar) __smallc;
extern bv_priority_queue_t __LIB__ *bv_priority_queue_init_callee(void *p,size_t capacity,size_t max_size,void *compar) __smallc __z88dk_callee;
#define bv_priority_queue_init(a,b,c,d) bv_priority_queue_init_callee(a,b,c,d)


extern size_t __LIB__ bv_priority_queue_max_size(bv_priority_queue_t *q) __smallc __z88dk_fastcall;


extern int __LIB__ bv_priority_queue_pop(bv_priority_queue_t *q) __smallc __z88dk_fastcall;


extern int __LIB__ bv_priority_queue_push(bv_priority_queue_t *q,int c) __smallc;
extern int __LIB__ bv_priority_queue_push_callee(bv_priority_queue_t *q,int c) __smallc __z88dk_callee;
#define bv_priority_queue_push(a,b) bv_priority_queue_push_callee(a,b)


extern int __LIB__ bv_priority_queue_reserve(bv_priority_queue_t *q,size_t n) __smallc;
extern int __LIB__ bv_priority_queue_reserve_callee(bv_priority_queue_t *q,size_t n) __smallc __z88dk_callee;
#define bv_priority_queue_reserve(a,b) bv_priority_queue_reserve_callee(a,b)


extern int __LIB__ bv_priority_queue_resize(bv_priority_queue_t *q,size_t n) __smallc;
extern int __LIB__ bv_priority_queue_resize_callee(bv_priority_queue_t *q,size_t n) __smallc __z88dk_callee;
#define bv_priority_queue_resize(a,b) bv_priority_queue_resize_callee(a,b)


extern int __LIB__ bv_priority_queue_shrink_to_fit(bv_priority_queue_t *q) __smallc __z88dk_fastcall;


extern size_t __LIB__ bv_priority_queue_size(bv_priority_queue_t *q) __smallc __z88dk_fastcall;


extern int __LIB__ bv_priority_queue_top(bv_priority_queue_t *q) __smallc __z88dk_fastcall;



#endif
