

	MODULE	tms9918_capabilities

	PUBLIC	__tms9918_CLIB_GENCON_CAPS
	PUBLIC	__tms9918_CAPS_MODE0
	PUBLIC	__tms9918_CAPS_MODE1
	PUBLIC	__tms9918_CAPS_MODE2

	INCLUDE	"ioctl.def"

        defc    __tms9918_CLIB_GENCON_CAPS = __tms9918_CAPS_MODE2
        defc    __tms9918_CAPS_MODE0 = CAP_GENCON_CUSTOM_FONT | CAP_GENCON_UDGS
        defc    __tms9918_CAPS_MODE1 = CAP_GENCON_CUSTOM_FONT | CAP_GENCON_UDGS
        defc    __tms9918_CAPS_MODE2 = CAP_GENCON_FG_COLOUR | CAP_GENCON_BG_COLOUR | CAP_GENCON_INVERSE | CAP_GENCON_CUSTOM_FONT | CAP_GENCON_UDGS | CAP_GENCON_UNDERLINE | CAP_GENCON_BOLD


