
// automatically generated by m4 from headers in proto subdir


#ifndef __ALLOC_BALLOC_H__
#define __ALLOC_BALLOC_H__

#include <stddef.h>

extern void *balloc_addmem(unsigned char q,size_t num,size_t size,void *p);
extern void *balloc_addmem_callee(unsigned char q,size_t num,size_t size,void *p) __z88dk_callee;
#define balloc_addmem(a,b,c,d) balloc_addmem_callee(a,b,c,d)


extern void *balloc_alloc(unsigned char q) __preserves_regs(b,c);
extern void *balloc_alloc_fastcall(unsigned char q) __preserves_regs(b,c) __z88dk_fastcall;
#define balloc_alloc(a) balloc_alloc_fastcall(a)


extern size_t balloc_blockcount(unsigned char q) __preserves_regs(b,c);
extern size_t balloc_blockcount_fastcall(unsigned char q) __preserves_regs(b,c) __z88dk_fastcall;
#define balloc_blockcount(a) balloc_blockcount_fastcall(a)


extern void *balloc_firstfit(unsigned char q,unsigned char numq);
extern void *balloc_firstfit_callee(unsigned char q,unsigned char numq) __z88dk_callee;
#define balloc_firstfit(a,b) balloc_firstfit_callee(a,b)


extern void balloc_free(void *p);
extern void balloc_free_fastcall(void *p) __z88dk_fastcall;
#define balloc_free(a) balloc_free_fastcall(a)


extern void *balloc_reset(unsigned char q) __preserves_regs(b,c);
extern void *balloc_reset_fastcall(unsigned char q) __preserves_regs(b,c) __z88dk_fastcall;
#define balloc_reset(a) balloc_reset_fastcall(a)



#endif
