
; int ba_priority_queue_empty_fastcall(ba_priority_queue_t *q)

SECTION code_clib
SECTION code_adt_ba_priority_queue

PUBLIC _ba_priority_queue_empty_fastcall

EXTERN asm_ba_priority_queue_empty

defc _ba_priority_queue_empty_fastcall = asm_ba_priority_queue_empty
